set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(ARM_NONE_EABI_GCC
    NAMES arm-none-eabi-gcc
    REQUIRED
)

get_filename_component(ARM_TOOLCHAIN_BIN_DIR "${ARM_NONE_EABI_GCC}" DIRECTORY)

find_program(ARM_NONE_EABI_AR
    NAMES arm-none-eabi-ar
    HINTS "${ARM_TOOLCHAIN_BIN_DIR}"
    REQUIRED
    NO_DEFAULT_PATH
)

find_program(ARM_NONE_EABI_RANLIB
    NAMES arm-none-eabi-ranlib
    HINTS "${ARM_TOOLCHAIN_BIN_DIR}"
    REQUIRED
    NO_DEFAULT_PATH
)

find_program(ARM_NONE_EABI_OBJCOPY
    NAMES arm-none-eabi-objcopy
    HINTS "${ARM_TOOLCHAIN_BIN_DIR}"
    REQUIRED
    NO_DEFAULT_PATH
)

find_program(ARM_NONE_EABI_SIZE
    NAMES arm-none-eabi-size
    HINTS "${ARM_TOOLCHAIN_BIN_DIR}"
    REQUIRED
    NO_DEFAULT_PATH
)

set(CMAKE_C_COMPILER "${ARM_NONE_EABI_GCC}" CACHE FILEPATH "ARM C compiler")
set(CMAKE_ASM_COMPILER "${ARM_NONE_EABI_GCC}" CACHE FILEPATH "ARM assembler")
set(CMAKE_AR "${ARM_NONE_EABI_AR}" CACHE FILEPATH "ARM archiver")
set(CMAKE_RANLIB "${ARM_NONE_EABI_RANLIB}" CACHE FILEPATH "ARM ranlib")
set(CMAKE_OBJCOPY "${ARM_NONE_EABI_OBJCOPY}" CACHE FILEPATH "ARM objcopy")
set(CMAKE_SIZE "${ARM_NONE_EABI_SIZE}" CACHE FILEPATH "ARM size")

set(CMAKE_EXECUTABLE_SUFFIX ".elf")
